-- Migration v1.7 — Discord Bot integration
-- Run via phpMyAdmin before deploying the bot

-- 1. Link Discord account to dashboard user
ALTER TABLE users
  ADD COLUMN discord_id VARCHAR(20) DEFAULT NULL UNIQUE
  COMMENT 'Discord snowflake ID, set by /link command';

-- 2. Short-lived codes generated by the dashboard for account linking
CREATE TABLE discord_link_codes (
  id         INT          AUTO_INCREMENT PRIMARY KEY,
  user_id    INT          NOT NULL,
  code       CHAR(6)      NOT NULL,
  used       TINYINT(1)   NOT NULL DEFAULT 0,
  created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP    NOT NULL,
  UNIQUE KEY uq_code     (code),
  INDEX      idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Invite tracking (one row per linked user)
CREATE TABLE discord_invites (
  user_id      INT       NOT NULL PRIMARY KEY,
  invite_count INT       NOT NULL DEFAULT 0,
  updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
